- .gitignore
- app/site/data/webpack.json
None
Removes and ignores app/site/data/webpack.json, which is generated by the webpack dev server and should not be in source control.
Rebuild the site using `docker-compose up --build` and make sure that webpack.json is ignored by git.
> Remove webpack dev server generated JSON

- src/webpack/webpack.common.js
had a small issue with the build path for webpack assets. this fixes it, so the built CSS ends up in the `dist` dir instead of `src/webpack/dist` (lol)
> fix path to 'dist'

- site/layouts/courses/baseof.html
- site/layouts/partials/header.html
- site/layouts/partials/mobile_nav.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/66
Moves mobile nav outside header partial and updates it to use the new menu structure.
Spin up the test site with `docker-compose up --build` and reduce window size to mobile width.  Clicking "Browse Course Material" should show the mobile nav with menu items populated.
> Mobile nav menu items fix

- package.json
- site/layouts/courseindex/baseof.html
- site/layouts/courses/baseof.html
- site/layouts/partials/mobile_course_info.html
- site/layouts/partials/mobile_nav.html
- site/layouts/partials/mobile_nav_toggle.html
- src/css/bootstrap-overrides.scss
- src/css/course-nav.scss
- src/css/drawer.scss
- src/css/main.scss
- src/index.js
- yarn.lock
https://trello.com/c/vjF0VNOk/26-mobile-course-navigation-drawer
https://trello.com/c/3ajMJlbT/25-mobile-course-info-drawer
this adds a second drawer, on the right-hand side, to hold the course info panel on mobile. It also adds a button for opening that drawer.
In order to get this to work I had to swap out our existing drawer component (which was from the bootstrap material design package). I tried out a few options before settling on this one: https://github.com/iamphill/Bootstrap-Offcanvas
try out navigating the course at various widths, especially tablet and phone widths. things should look alright and work well.
> mobile drawers (course nav and course info)

- src/webpack/webpack.common.js
- src/webpack/webpack.dev.js
config tweak
turn of the 'watchContentBase' option in the development webpack config. basically, having this option on meant that every time the hugo site rebuilt, because a template is saved or whatever, every single file being written in the `/dist` dir gets picked up by weback. on my computer this causes the tab that the site is open in to lock up completely.
turning off the content watch mode fixes this. the downside is that after saving a template change the browser will not automatically refresh, but that's alright.
> turn off webpack watching the `/dist` folder, since it gets too heavy

- docker-compose.yml
- package.json
- site/layouts/courses/baseof.html
- src/webpack/webpack.dev.js
none
tooling change, this sets us up to use the hugo server instead of using webpack to serve html.
this is nice, because `hugo server` has a built-in live-reloading thing which is very fast. it seems to work just fine alongside the webpack hot-reloading as well.
to get this to work I basically just:
- changed hugo to use the `server` option instead
- changed webpack's port to `3001`
- made a small change to our `baseof` template that looks at the `.Site.IsServer` variable to figure out whether to make a request for the CSS and JS assets from the webpack dev server or from the compiled asset.
dev env should work normally
> switch from using webpack as main server to using hugo

- site/layouts/courseindex/baseof.html
- site/layouts/courses/baseof.html
- src/css/main.scss
closes #90 
this basically fixes up how we style tables in the markdown content so that they don't blow up the scrolling on the page
try a course like <localhost:3000/courses/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/sections/day-1-identity-and-genre/>
make sure that the table itself scrolls horizontally on mobile, but that it doesn't take all the page content with it.
> fix table overflow

- .eslintrc
- src/css/main.scss
- src/css/theme-one.scss
- src/index.js
- src/js/stylesheets.js
no gh ticket
this basically adds a 'theme' engine of sorts that allows the user to dynamically switch between a few different stylesheets. it adds a little drop-down in the upper right hand corner of the page. selecting an option in the dropdown sets a class on the `html` element, which can then by used to style the page differently.
Just for testing purposes I included a lovely theme that makes things pink and uppercase.
You should be able to switch between the two themes. changes should take effect immediately. your selection should persist across refreshes.
note that there is a brief flash before the JS is executed when you have the pink theme selected - imo this is not something to worry about.
> add stylesheet switcher

- site/layouts/courses/section.html
- site/layouts/partials/course_image.html
- site/layouts/partials/course_instructor_number.html
- src/css/main.scss
in trello
this fixes the rendering of the course image, title, etc on the course home page to be in line with the mocks.
check out the course home page and make sure it looks good! the mobile page should be unchanged.
> fix course image display on desktop

- site/layouts/courses/baseof.html
- site/layouts/courses/section.html
- site/layouts/partials/topic.html
- src/css/gitbook.scss
none
this gets the sidebar styling more gitbook-ey-looking
just try it out and make sure it looks alright to you
for comparison, this is the sidebar on gitbooks:
> make sidebar look more gitbook-ey

- site/layouts/partials/pdf_viewer.html
- src/css/main.scss
- src/css/pdf.scss
none, just a styling tweak on the PDF viewer
this restyles the wrapper div and the PDF viewer so that it has a fixed aspect ratio (see screens below) which will ensure that when you open a PDF page by default you see the first whole page of the PDF. And also that you can scroll to view a whole page at a time, instead of the aspect ratio getting a little wonky.
try it out and make sure it works alright! should be good on mobile too.
> make PDF viewer have a fixed aspect ratio at all widths

- site/layouts/partials/course_instructor_number.html
https://trello.com/c/sCn5mXiU/78-align-instructor-and-course-number-tags-with-the-header
The `p-md-2` class was removed from table cells that were using it in `course_instructor_number.html` and `px-0 py-2` was used in its place.  Individual spacing rules like `px-0` do not automatically take precedence if you are including a class like p-md-2 because all of these spacing rules use `!important` under the hood.
Run the site or visit the deploy preview, verify that the alignment is correct.
> Fix instructor / course no. title spacing

- site/layouts/partials/course_instructor_number.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/117
Fixes the course number display on course pages so they show up as a comma separated list of clickable links.
Run the site or visit the deploy preview.  View different course pages and verify that the course number links appear as expected, and that they say coming soon when you click them.
> Fix course number display outside of course info partial

- site/data/course_annotations.json
- site/layouts/courseindex/section.html
none
just adds some info to our sort of temporary course list
go to `/courses` and you should see annotations for some of the courses and they should all have a course number.
┆Attachments: <a href="https://github.com/mitodl/hugo-course-publisher/issues/123">#123 Annotate course listing page</a>
> Annotate course listing page

- src/css/main.scss
Closes https://github.com/mitodl/hugo-course-publisher/issues/150
Adds a `left-margin` rule to `blockquote` elements to match current OCW
Run the site, verify that blockquotes like this one are indented:
http://localhost:3000/courses/20-020-introduction-to-biological-engineering-design-spring-2009/sections/syllabus/
> blockquote left-margin

- site/layouts/_default/pdf.html
- site/layouts/_default/section.html
- site/layouts/_default/single.html
- site/layouts/_default/video.html
- site/layouts/_default/videogallery.html
- site/layouts/partials/course_section.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/168
This PR corrects a few spots I missed that need to use `chp_partial.html` to get access to the context of the course home page.
Run the site.  The instructor and course numbers should now be visible from pages other than the course home page.
> fix instructor and course number

- site/layouts/course/pdf.html
- site/layouts/course/video.html
- site/layouts/course/videogallery.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/176
These templates were moved into the `course` type, and they don't need to call partials with the `chp_partial.html` partial.
Run the site, visit http://localhost:3000/courses/14-01sc-principles-of-microeconomics-fall-2011/sections/unit-3-producer-theory/productivity-and-costs/ or any other pdf, videogallery or video page.  You should see the content from the page and not the course home page.
> videogallery / video / pdf bug fix

- README.md
- src/webpack/webpack.common.js
none
set dotenv to pull in system variables too
search should work in the deployed environment
> fix search environment variable issue

- src/js/lib/search.js
- src/js/lib/search.test.js
part of #178 
this basically changes the elasticsearch query generation code to limit the results to just courses, and exclude other learning resources which could be returned otherwise (videos, podcasts, etc).
make sure that on your local instance you have some OCW courses as well as other OCW stuff, and then confirm that after checking out this branch you're only seeing courses in your search results.
> limit OCW search to return only courses

- README.md
Add a note to the README about configuration of CORS access within the Open Learning app, to allow the OCW frontend search code to post requests to it.
> Add note to README about CORS w.r.t. the search endpoint

- package.json
https://github.com/mitodl/hugo-course-publisher/issues/191
Adds a convenient command to the node build scripts to build the whole site against an external content directory
Build content in `ocw-to-hugo` using the output of [this](https://github.com/mitodl/ocw-to-hugo/pull/66) PR (or master after it merges) and then point to the output directory using the following syntax:
```sh
npm run build:externalcontent -- /path/to/content
```
> add build:externalcontent command

- site/config.toml
https://github.com/mitodl/hugo-course-publisher/issues/204
This PR sets `relativeUrls` to false in the Hugo `config.toml` file.  When building the whole site with output from `ocw-to-hugo` with the `strips3` option enabled, the Hugo build would balloon in memory usage until eventually crashing out.  This is because `strips3` turns every link into an absolute link relative to the site root, which Hugo processes and tries to turn into a relative link.
Sync the entire `open-learning-course-data-production` bucket to your local machine and run `ocw-to-hugo` with the `strips3` option enabled.  Then, run the `hugo-course-publisher` build with the output from this run and ensure you do not get an out of memory error.
> disable relativeUrls by default

- site/layouts/partials/course_content.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/212
Removes the instructor and course number from pages that aren't the course home page.
Run the site, verify that course number and instructor do not show up on pages that aren't the course home page.
> hide instructor and course number from section pages

- site/layouts/partials/course_instructor_number.html
- site/layouts/partials/partial_collapse_list.html
- src/css/variables.scss
Closes https://github.com/mitodl/hugo-course-publisher/issues/220
This PR increases `$partial-collapse-height` to `6em` which fully reveals 3 items in a list and partially reveals a fourth.  The threshold has also been changed to 4 items, so a list needs to contain more than 4 items to have this style applied.
Run the site or visit the deploy preview and look at a course like `16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006` that has a lot of instructors and verify that it displays them as noted in the issue above.
> set partial collapse list to reveal 4 items

- src/css/learning-resource-card.scss
- src/js/components/HomeSearchBox.js
- src/js/components/SearchPage.js
- src/js/components/SearchResult.js
- src/js/components/SearchResult.test.js
- src/js/lib/constants.js
this follows the behavior that we do in Open, where you can click on a topic in the result card to go a search for that topic.
check out the branch and check that you can click on, say, 'physics' on a card and be linked to `/search/?t=Physics`.
> link from topics in search results to a search with that topic

- src/css/search-filter.scss
- src/js/components/SearchPage.js
for #226 
this decreases the space between the filter and the search results to be more in line with the designs (look [here](https://projects.invisionapp.com/d/main#/console/18609637/430757993/inspect) for instance).
just check out the branch and make sure the spacing is more in line with the design.
> fix spacing between topic filter and results

- package.json
- yarn.lock
for #226
this downgrades the `react-dotdotdot` package to the same version we're using in Open. The newer version doesn't seem to recalculate whether it should truncate or not correctly (only on re-render, not if a hover state changes, for instance). The older version does better, and solves one of the issues listed in #226.
If you check out this branch you should note that hovering over the facet values in the topic picker doesn't cause two lines to appear, like this:
> downgrade react-dotdotdot

- package.json
- src/js/components/Loading.js
- src/js/components/Loading.test.js
- yarn.lock
part of #226
this replaces the little 'spinner' animation we're currently using with a 'placeholder' animation that is similar to the ones we use in Open.
I think just make sure that the animation is showing up and so on.
> pull in open-style loading animation

- src/js/components/Loading.js
- src/js/components/Loading.test.js
- src/js/components/SearchPage.js
none
fix an issue where the loading placeholder was always being shown below the search results. This was happening because I was inadvertantly passing the same `<Loader />` component in to the `<InfiniteScroll>` component and using it as a loading placeholder.
To fix it, I brought the spinner we had back to use for showing at the end of the search results and keep the loading placeholder just for the initial load.
use the course search and then scroll down, you should see the loading placeholder on first load but then after that you should just see a simple spinner while the next page is being loaded.
> fix search issue w/ loader

- src/css/search-filter.scss
- src/css/search.scss
closes #226 
this fixes an issue where the placeholders are located strangely in the inputs in firefox (not in chrome). this is what it looks like:
this PR just applies some CSS to fix it (hackily).
just check out the branch and make sure the placeholders look good I think.
> fix input placeholder issues in firefox

- src/js/components/SearchPage.js
None
I saw this warning on master:
I added the `key` prop to the `<Spinner />` component and the warning went away. It looks like `InfiniteScroll` adds the `loader` prop value to a list of values to be passed to render which is probably where the error comes from. The [InfiniteScroll docs](https://github.com/danbovey/react-infinite-scroller#readme) say that you need a key prop when passing in a loader component.
You shouldn't see a warning when viewing the course search page. You should see it on master.
> Fix React warning for key prop

- site/layouts/shortcodes/fullwidth-cell.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/219
This PR, in combination with the output of https://github.com/mitodl/ocw-to-hugo/pull/85, fixes header cells in tables so they do not break the layout of the table.
Run the site with the output of the `ocw-to-hugo` PR above and ensure that the tables are displaying properly.
> add the fullwidth-cell shortcode

- .gitignore
- package.json
- src/js/components/FilterableFacet.js
- src/js/components/SearchPage.js
- src/js/components/SearchPage.test.js
- src/js/lib/search.js
- src/js/lib/search.test.js
- yarn.lock
closes #217 
This PR adds another FilterableFacet for filtering results based on their department. It works the same as our existing 'Topics' facet.
Try it out and make sure you can change the value selected in the facet, that the search updates as you'd expect, and so on. The values selected should be persisted to the URL under the `d` search param (`d` for department!).
> add department facet to search

- .dockerignore
- .gitignore
- Dockerfile
- build-scripts/build_course_zips.js
- docker-compose.yml
- package.json
- src/js/helpers.js
- src/js/helpers.test.js
Fixes #195 
This fixes an issue where zips were populated within the area that hugo picked up files, causing a feedback loop which ran out of memory. I also changed the zip processing to use the zip command in case there were any memory leak issues with archiver.
Run `npm run build:zips` and verify the output zip files look right. This took an hour on my laptop, though it could be faster on other hardware, and we could run tasks in parallel in a future PR if necessary.
> Fix zip memory issue

- README.md
- package.json
None
This PR fixes a rebase issue that blew away `COURSE_ZIPS_DESTINATION` in the package.json `build:zips` script and also documents the use of the variable in the readme.
ensure that `COURSE_ZIPS_DESTINATION` is properly passed to the script and that the readme changes make sense.
> put back COURSE_ZIPS_DESTINATION and document it

- src/js/lib/search.js
- src/js/lib/search.test.js
- src/js/test_setup.js
Fixes #238 
If `CDN_PREFIX` environment variable is not set, the S3 URL is left alone
- If you don't have this data set up already, run `sync_ocw_courses(course_prefixes=["PROD/6/6.046/Fall_2005/6-046j-introduction-to-algorithms-sma-5503-fall-2005/"], blocklist=[], force_overwrite=True, upload_to_s3=True)` to populate that course in the resources list
- Go to `/search`, click "Resources" and search for "6-046j".
- Hover over the link for the PDF item in the search results. If you have set `CDN_PREFIX`, it should start with `/coursemedia`. If not, it should be a regular S3 link
> If CDN_PREFIX is not set, don't use a CDN URL

- src/js/components/SearchResult.js
- src/js/components/SearchResult.test.js
- src/js/lib/search.js
- src/js/lib/search.test.js
Closes #259 
- Handles course search results with no runs without blowing up the page
- Tests should pass
- Delete all the runs from a published OCW course in open, update in ES, then search for it here by title.  It should show up in the raw search results response but be excluded from results.
> Handle bad course results with no runs

- src/css/button.scss
- src/css/search-filter.scss
- src/css/variables.scss
- src/js/components/FacetDisplay.js
- src/js/components/FacetDisplay.test.js
- src/js/components/SearchFilter.js
- src/js/components/SearchFilter.test.js
- src/js/components/SearchFilterDrawer.test.js
- src/js/components/SearchPage.js
closes #256
this adds little buttons to show the filters that you currently have enabled and allow the user to remove them one by one or remove all of them. it's very similar to what we have on the course search on Open.
Go check out the search. When you click one of the facet options you should see a little thingy (shown below) show up that you can then click to remove it. the '
> add buttons to show currently applied facets, allow for clearing them

- src/js/components/SearchPage.js
- src/js/components/SearchPage.test.js
Closes #265 
When switching the search page from courses to resources, clear the department and topic facet choices (but not the text query).  This is written in such a way that if courses and resources share some of the same facets in the future, those shared facet choices will not be cleared when switching.
- Search for courses using a text query and 1 or more department & topic facets.  
- Switch to resource search.  The facets should be cleared but not the text query (look at the URL).
> Clear type-specific facets when switching between resources and courses

- site/layouts/partials/topics_summary.html
- site/themes/multi_course/layouts/home.html
- src/css/home.scss
Fixes #240 
Adds four course cards to the home page using data from the course frontmatter
- Use an updated version of ocw-to-hugo to create markdown for the site. It needs to include https://github.com/mitodl/ocw-to-hugo/pull/101 and https://github.com/mitodl/ocw-to-hugo/pull/102
- View the homepage. You should see up to 4 course cards sorted from most recently published
See comment below
> Add course cards to home page

- package.json
- src/js/components/SearchPage.js
- src/js/components/SearchPage.test.js
- src/js/lib/search.js
- src/js/lib/search.test.js
- yarn.lock
closes #216 
This adds support for the 'level' facet, by upgrading course-search-utils and making some changes to the code used to generate the ES query.
You'll need to check out this PR on open: https://github.com/mitodl/open-discussions/pull/3187
then you should be able to use the level facet on the OCW course search. It should work as you'd expect, and shouldn't interact weirdly with the other facets.
> add level facet

- src/js/components/SearchResult.js
- src/js/components/SearchResult.test.js
closes #270
this fixed an issue where the `<a>` tag that points to the course wasn't occupying the full width of the `.course-title` div. this puts the width to 100% to ensure that you can click anywhere in the `.course-title` div and get to the course.
check out the branch, and ensure the behavior described above works!
> fix search result title width

- site/layouts/partials/home_course_cards.html
- site/themes/multi_course/layouts/home.html
- src/css/home.scss
Fixes #268 
Implements the bootstrap course carousel for course cards. This is rendered twice, once for desktop and once for mobile, and we use CSS to show one or the other depending on the breakpoint.
View the homepage and resize the browser to see how different breakpoints react
Desktop:
Tablet width. Note that the user will need to scroll to see all the cards. The carousel is effectively the same as for desktop.
Wide mobile
Narrow mobile
> Add bootstrap carousel for course cards

- site/layouts/partials/course_info.html
- site/layouts/partials/partial_collapse_list.html
- site/layouts/partials/topic.html
- src/index.js
- src/js/course_info_links.js
#273
this re-writes the `href` of the links in the course info side panel to link to the search with the relevant parameter and value pre-selected. so if you click for instance 'Undergraduate' in the panel you'll go to `/search/?l=Undergraduate`.
The rewriting happens in JS because I figured that was DRYer.
In this PR I'm addressing the level, topic, and department values because those ones don't require extra search work. I'll circle back for the instructor one.
check out a course page and make sure you can click on those three types of values and that it takes you to a relevant search page. other values in the course info panel (like instructor, course no., or 'taught in') should still have the "Coming soon!" behavior when clicked.
> link from course info to search

- site/layouts/partials/home_course_cards.html
- src/css/home.scss
Fixes #288 
Tweaks CSS to widen the course cards to 300px on the wide desktop view. However, the xl breakpoint starts at 1200px so we can't show 4 cards at this width, so at this width it is somewhere closer to 270px. Once it goes below 1200px it becomes 2 cards wide. What do you think @abdulkdawson @pdpinch?
View the home page and resize the browser width
These are both of the full browser window:
Narrow desktop view:
Wide desktop view:
> Tweak course cards to be 300px wide on desktop view

- src/css/search.scss
- src/js/components/SearchPage.js
- src/js/components/SearchPage.test.js
- src/js/lib/util.js
part of #178 
this adds a basic 'suggestion' UI, along the lines of what we do in Open course search.
Make a typo in the search, like "sceince", "mothemotics", or something similar. you should get a little suggestion for what you mean, and click on it should change to the search text to that suggestion.
> add suggestions UI to Search

- package.json
None
Adds a command to create `static/hash.txt` when `npm run build:netlify` is run. This should add `static/hash.txt` to CI deployments similar to how it works for RC and production.
It's probably easiest to merge first, then check CI to verify that `static/hash.txt` was created.
> Enable static/hash.txt for CI deployment

- src/js/factories/search.js
- src/js/lib/search.js
- src/js/lib/search.test.js
Closes #303
Instead of assuming the first run in a course is the best run to link to, exclude unpublished runs and find the run with the most recent start date.
In open-discussions, import 3 runs for course 18.01 if they aren't already imported:
```python
from course_catalog.api import sync_ocw_courses
sync_ocw_courses(course_prefixes=[
"PROD/18/18.01/Fall_2003/18-01-single-variable-calculus-fall-2003/",
"PROD/18/18.01/Fall_2005/18-01-single-variable-calculus-fall-2005/",
"PROD/18/18.01/Fall_2006/18-01-single-variable-calculus-fall-2006/"
], blocklist=[], force_overwrite=True, upload_to_s3=False)
```
Then search for 18.01 in OCW.  Click the course link in the first result, it should bring you to http://localhost:3000/courses/18-01-single-variable-calculus-fall-2006/
> Link to the most recent published course run url

- README.md
- site/layouts/partials/course_info.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/310
This PR removes the "Download Course Materials" buttons from the `course_info.html` partial.  Course zip building functionality remains intact, but the readme has been updated to only convey that the archives are generated and not linked in the site.
Run the site or visit the deploy preview and ensure that you don't see the Download Course Materials buttons.
> remove "download course materials" buttons

- site/layouts/course/baseof.html
- site/layouts/partials/course_features.html
- site/layouts/partials/course_info.html
- site/layouts/partials/topics.html
Related to https://github.com/mitodl/hugo-course-publisher/issues/312
This PR splits up the elements in `course_info.html` into 3 separate partials so they can be rearranged based on the new designs.
Spin up the site or visit the deploy preview.  Each Course Info section should render exactly as before.  You should see no difference.
> split up course_features.html

- site/layouts/partials/course_info.html
- site/layouts/partials/course_instructor_number.html
- site/layouts/partials/partial_collapse_list.html
closes #307 
makes it so that the course number and the 'As taught in' aren't links any longer (this incidentally removes the 'coming soon...' behavior as well)
check out a course page and make sure that both the course number and the 'as taught in' aren't links any longer.
> remove links from Course no., "As Taught In" in course info

- site/layouts/partials/course_info.html
- site/layouts/partials/course_instructor_number.html
- src/js/components/SearchResult.js
- src/js/course_info_links.js
- src/js/course_info_links.test.js
Closes #306 
Adds search links to each professor name in 3 places: course info sidebar, course home page instructor list, and search result cards.
Each instructor name near the top of each course home page, the sidebar for each course page, and in each search result card should link back to the course search page with a parameter of `q="<first_name last_name>"`.  The department and level links should work the same as before.
> Instructor search links

- site/layouts/partials/topic.html
- src/js/course_info_links.js
- src/js/course_info_links.test.js
Closes #309 
Re-enables the topic search links
Click on the topics at each of the 3 levels in the sidebar of a course page.  You should be redirected to the search page with that topic selected.  If you have run `backpopulate_ocw_topics` in open-discussions, the 3rd level topic should return some search results.
> Re-enable topic search

- site/config.toml
- site/config_zip.toml
- site/content/_index.md
- site/layouts/_default/baseof.html
- site/layouts/course/baseof.html
- site/layouts/partials/title.html
- src/js/components/SearchBox.js
- src/js/components/SearchBox.test.js
Fixes #321 
Fixes #255 (unrelated but one line change)
Updates handling of page titles. Here's the algorithm:
- All pages will have the site title. There is also "Free Online Course Materials" if there are 3 or fewer items in the title. The home page title: `MIT OpenCourseWare | Free Online Course Materials`
- If there is a title in the front matter, it will go first. For example, the search page: `Search | MIT OpenCourseWare | Free Online Course Materials`
- If the page is a course page, it will use the course title, then the department, then the site title. For example: `DNA&#39;s Sister Does All the Work: The Central Roles of RNA in Gene Expression  | Biology | MIT OpenCourseWare`
- If a page has both course information and a title in the front matter, then the front matter title will …
> Set page titles

- site/layouts/partials/mobile_course_info.html
None
When the `course_info.html` partial was split up into its 3 parts, I forgot to reflect those changes in the mobile course info drawer.  This adds them back.
Run the site and assure you can see topics and course features in the mobile course info drawer.
> add back in topics and features in the mobile course info drawer

- site/layouts/course/baseof.html
- src/css/course-nav.scss
- src/index.js
- src/js/course_info_toggle.js
- src/js/lib/constants.js
Related to https://github.com/mitodl/hugo-course-publisher/issues/311
This PR adds a hide / show button to the course info section on the right side of the desktop layout.  When collapsed, the main content area fills the space left over.
Run the site and visit a course page in every browser you have access to, testing that the button properly collapses and expands the course info section on the right.
> desktop course info toggle

- src/css/search-filter.scss
closes #337
changes a CSS rule so that the text in the filter 'bubbles' will wrap (see screenshots if that doesn't make sense)
make sure that some of the long titles work alright.
this is a good filter to test:
http://localhost:3000/search/?d=Electrical%20Engineering%20and%20Computer%20Science
before:
after:
mobile:
:tada:
> fix search filter title wrapping

- package.json
- site/layouts/shortcodes/simplecast.html
- yarn.lock
closes #335 
this adds support for the `simplecast` shortcode that I added in https://github.com/mitodl/ocw-to-hugo/pull/122
you'll need to import a course with ocw-to-hugo that has a simplecast embed in it. the one I know of is `15-667-negotiation-and-conflict-management-spring-2001`.
then if you have that course imported locally you should be able to visit http://localhost:3000/courses/15-667-negotiation-and-conflict-management-spring-2001/sections/instructor-insights/. On master you should see just the page text with no audio embed, but on this branch there should be a podcast UI like what is shown in the screenshots below.
> upgrade ocw-to-hugo, add support for simplecast

- src/js/course_info_toggle.js
None
Fixes an exception which is thrown when code looks for the course info toggle button, which doesn't exist on every page
You should not see a console error when visiting the home page
> Don't activate desktop toggle for other pages

- package.json
- site/layouts/partials/topic.html
- site/layouts/partials/topics.html
- site/layouts/partials/topics_summary.html
- yarn.lock
Fixes #345 
Updates partials to use different data structure for topics from https://github.com/mitodl/ocw-to-hugo/pull/119. This preserves the case sensitivity of the topic and subtopic, which allows searches to match more correctly.
You'll need to use an updated version of the parsed JSON to create markdown, from ocw-to-hugo 1.3.1 or later. If you just switch from master to this branch without recreating the markdown you should see some errors about `topics.html`. 
Nothing should look different. In particular you should see topics on the course cards and the topic expander items on the course home page. All topic links should work as before.
> Update topics partials to use new data structure

- site/themes/multi_course/layouts/home.html
- src/css/home.scss
none
1. fix issue with background-image on the home banner by setting an inline HTML style instead of CSS
2. fix height of course card image on homepage
look at it
> fix two style oopsies

- site/layouts/partials/course_content.html
- src/css/main.scss
Related to https://github.com/mitodl/hugo-course-publisher/issues/311
This PR alters the text styling in course section pages' content to match these mocks:
https://projects.invisionapp.com/d/main/#/console/18609637/435659054/inspect
https://projects.invisionapp.com/d/main/#/console/18609637/435659055/inspect
Note that the alternating grey backgrounds in the mock are currently not feasible and are not included in this PR.
Run the site or visit the deploy preview and ensure that everything looks as it should
> course page content text style

- site/layouts/course/baseof.html
- site/layouts/course/course_home.html
- site/layouts/course/course_section.html
None
Fixes a bug where the header does not display properly on video and pdf pages
Run the site and visit the deploy preview, ensure that the header is being rendered properly.  Here are a few examples:
http://localhost:3000/courses/ec-711-d-lab-energy-spring-2011/sections/intro-energy-basics-human-power/mitec_711s11_read_react/
http://localhost:3000/courses/ec-711-d-lab-energy-spring-2011/sections/week-7-trip-planning-and-preparations/lecture-7-solar-cookers-creative-capacity-building-trip-preparation/
> fix header and course_banner usage

- src/css/home.scss
Fixes #380 
Adjusts `course-card` image radius to match the image border radius
Look at the cards
There are still some stray pixels leaking out. I'm not sure how to fix or if it's worthwhile to do so:
> Adjust border radius of carousel card to match image

- example_courses.json
none
add a series of courses which have had some issue at some point which we fixed. There was the matlab course, where we had a code block issue, a course with a simplecast embed, etc.
this should make it so that the example course set, used in development, is more representative of the range of things that we actually render on the full site.
Make sure that you can run `import:ocw:example_courses` and then build the site without errors.
> expand example_courses.json

- site/layouts/course/course_home.html
- src/css/course-home.scss
closes #395
we were rendering the alt text as the caption previously. this instead renders the alt text for the course image as alt text, and renders the caption text in the caption.
check out a few courses. the image captions should be rendered correctly on the course home page, and the image should also have appropriate alt text.
show the image highlighted in the issue:
> fix image caption / image alt text issue

- site/layouts/course/baseof.html
- site/layouts/partials/course_banner.html
- src/css/header.scss
none, Ferdi just said we want to do this
this makes the text in the course header (the title with blue background at the top) into a link to the course home page.
you should just make sure it's there and the link works correctly from all course pages.
I couldn't get this to work with the `chp_partial` so I followed the way we do it for the nav partial - possibly this is an incorrect approach but I couldn't get past an error I was getting with the `chp_partial`.
> make the course banner text a link to the course home page

- site/layouts/partials/course_info.html
- src/css/course-info.scss
- src/index.js
- src/js/course_expander.js
Part of #312 
Adds a button to toggle course info
Click the expander button
Desktop:
Mobile:
> Implement collapse/expand for course info

- site/layouts/partials/home_course_cards.html
closes #369
adds a link to wrap around the course images, so the user can click on them.
visit the home page, and you should be able to click through to various courses by clicking on their images in the course carousel.
> carousel image should be a link too

- site/layouts/partials/course_feature.html
closes #385
this just tweaks the spacing around the icons and the text for the 'course features' widget, to match the mockup more closely.
Just make sure it looks alright to you I think.
> fix course feature spacing

- site/layouts/partials/home_course_cards.html
- src/css/home.scss
closes #368
this adds the `.card` class to our course-cards on the home page, so that they get the hover effect that we want.
check out the homepage at a variety of widths. Make sure that the cards have a box-shadow when you hover over them, and that nothing is too weird.
> add hover effect, add some padding so it's visible

- site/themes/multi_course/layouts/partials/chp_partial.html
- site/themes/single_course/layouts/partials/chp_partial.html
Closes https://github.com/mitodl/hugo-course-publisher/issues/372
Removes both the `multi_course` and `single_course` versions of `chp_partial.html` as it's no longer necessary since course metadata is now being stored in Data Templates.
Make sure the site still builds okay, ensure you see no references to `chp_partial.html`
> remove chp_partial.html

- site/layouts/course/course_home.html
- src/css/course-info.scss
- src/js/course_expander.js
Fixes #312 
This implements the read more link in the issue which should finish the items listed in #312. I added `react-clamp-lines` since there wasn't an obvious vanilla JS or CSS way to do this and the package doesn't pull in any other dependencies.
The course description is part of the original HTML. The JS will take that HTML, remove the original copy, and render it as a react element with `ClampLines`. `ClampLines` deals with raw text so I made a modification allowing it to display the original html if the description was expanded. There is some DOM manipulation from the React component so let me know if anything appears to glitch.
Caveats: This won't look quite right if there is an image at the top of the course description. Also, the "Read more" and "Show less" links will appear …
> Add read more link for course description

- src/js/components/SearchResult.js
- src/js/components/SearchResult.test.js
- src/js/factories/search.js
- src/js/lib/search.js
~~Blocked by https://github.com/mitodl/open-discussions/pull/3245~~
Related to https://github.com/mitodl/open-discussions/issues/3243
Uses `coursenum` from search results instead of `course_id` for the course number in the search result card subtitle
- Reindex open-discussions after PR https://github.com/mitodl/open-discussions/pull/3245 is applied.
- Search for courses for "18.01", you should get back 2 results, same title with different thumbnails, and the subtitle on the results should show "18.01" and not something like "aef8923sdfdf12+18.01"
> Use coursenum instead of course_id in search results

- site/layouts/course/course_home.html
Fixes a merge conflict affecting #410 
Updates the CSS class
The read more link on the course description should expand and contract on a course home page
> Fix CSS Typo for read more link on course description

- src/css/search.scss
- src/js/components/SearchResult.js
Partially addresses #409 
Prevents a multi-word topic from being split into multiple lines, adds commas, and underlines the links.
Go to the search page, try it out in desktop and mobile view.
> Nowrap and underline topic links

- site/assets/navigation.js
- site/layouts/course/baseof.html
- site/layouts/partials/nav.html
- site/layouts/partials/nav_item.html
- site/layouts/partials/navigation_js.html
none, working on speeding up the hugo build.
implements a nav solution for the course pages which can be cached across courses. it is still recursive, to render the children and so on, but figuring out when links should have `.active` and when the sections should be expanded is now done with a simple JS function instead of in Hugo. This means that the partial can be rendered just once per course.
I wrote a small JS function to do the work of applying `.active` and so on. Putting it in the webpack JS bundle lead to some yuckiness where the user would see a little flash, since `.active` is applied a bit after startup. So to get around that I experimented with just writing the function directly in the `<script>` tag in the course `baseof.html` template. That worked well, but I think we don't …
> speedier nav implementation

- .github/workflows/deploy.yml
- build-scripts/formatLighthouseComment.js
closes #367 
this reconfigures our netlify PR and CI builds to be done through github actions, instead of netlify's automatic integration, and then on PRs runs google pagespeed on the completed build.
I have it set up right now to write a simple comment on the PR with the results of the pagespeed run. The code written here for the action could also be repackaged as our own custom action if we want to add this to other repositories.
Review the .yml stuff carefully for any errors in logic and so on. The github actions documentation [here](https://docs.github.com/en/free-pro-team@latest/actions/reference) may be helpful for doing so.
I wrote logic here to deploy the CI build (<https://ocw-next.netlify.app/>) but I don't have a way to test it without merging to master, so we'll have to just …
> github actions for netlify, google pagespeed

- package.json
- yarn.lock
https://github.com/mitodl/hugo-course-publisher/issues/436
This PR updates `ocw-to-hugo` to 1.7.0, which includes a change to ignore unpublished courses.
Just make sure the site installs dependencies properly and spins up with:
```
yarn install
npm start
```
> update ocw-to-hugo to 1.7.0
