mitodl/hugo-course-publisher

- app/package.json
- app/webpack.prod.js
- app/yarn.lock
https://github.com/mitodl/hugo-course-publisher/issues/43
Replaces the uglifyjs webpack plugin with the terser plugin.
Build the site and there should be no errors.
> Replace uglifyjs with terser

- site/layouts/courses/baseof.html
- site/layouts/courses/section.html
- site/layouts/courses/single.html
- site/layouts/partials/breadcrumb.html
- site/layouts/partials/desktop_nav.html
- site/layouts/partials/mobile_course_info.html
- site/layouts/partials/mobile_nav.html
- site/layouts/partials/mobile_nav_toggle.html
- site/layouts/partials/nav.html
- src/css/course-nav.scss
- src/css/desktop-nav.scss
- src/css/header.scss
- src/css/main.scss
(Required)
this has some general tweaks I was doing for the mobile UI as I was working on the mobile version of the course info.
doing the course info is going to require more substantial tweaks, so I wanted to go ahead and put what I had so far up for review.
check out the mobile view. you should be able to open the course materials drawer by clicking on the button. Additionally, spacing for things should mostly make sense on mobile.
> basic tweaks for the mobile UI

- .gitattributes
no ticket, just a github config change
> add a gitattributes to make markdown diffs more manageable in github

- site/layouts/courses/section.html
none
fix a small issue with the course section template (used to render the course home page).
make sure that the content specific to the course home page is showing up!
> fix a small bug on course/section.html template

- site/content/courses/12-001-introduction-to-geology-fall-2013/_index.md
- site/content/courses/15-071-the-analytics-edge-spring-2017/_index.md
- site/content/courses/15-s21-nuts-and-bolts-of-business-plans-january-iap-2014/_index.md
- site/content/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/_index.md
- site/content/courses/18-01sc-single-variable-calculus-fall-2010/_index.md
- site/content/courses/18-06-linear-algebra-spring-2010/_index.md
- site/content/courses/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/_index.md
- site/content/courses/21g-049-french-photography-spring-2017/_index.md
- site/content/courses/21m-250-beethoven-to-mahler-spring-2014/_index.md
- site/content/courses/21m-295-american-popular-music-fall-2014/_index.md
- site/content/courses/5-111sc-principles-of-chemical-science-fall-2014/_index.md
- site/content/courses/6-033-computer-system-engineering-spring-2018/_index.md
- site/content/courses/6-042j-mathematics-for-computer-science-spring-2015/_index.md
- site/content/courses/8-01sc-classical-mechanics-fall-2016/_index.md
- site/content/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/_index.md
- site/content/courses/8-06-quantum-physics-iii-spring-2005/_index.md
- site/content/courses/8-591j-systems-biology-fall-2014/_index.md
- site/content/courses/ec-711-d-lab-energy-spring-2011/_index.md
- site/content/courses/res-15-002-mission-metrics-finance-training-for-federal-credit-program-professionals-summer-2016/_index.md
- site/content/courses/res-15-003-shaping-the-future-of-work-15-662x-spring-2016/_index.md
- site/content/courses/res-2-005-girls-who-build-make-your-own-wearables-workshop-spring-2015/_index.md
- site/content/courses/res-2-006-girls-who-build-cameras-summer-2016/_index.md
- site/content/courses/res-3-004-visualizing-materials-science-fall-2017/_index.md
- site/layouts/partials/course_info.html
https://trello.com/c/RQRqs9FQ/35-topic-subtopic-specialty
Updates the sample content to reflect changes made to ocw-to-hugo to generate topic > subtopic > speciality for topics and other locations that use the course_collections objects from master.json.
Run the site, confirm that specialities are being rendered.
> Update sample content topics with speciality

- package.json
just adding a script to `package.json`
> add a little shortcut for running some debug / statistics things on hugo

- site/layouts/courses/baseof.html
- site/layouts/courses/section.html
(Required)
(Required)
(Required)
(Optional)
(Optional)
(Optional)
> remove `<base>` tag to fix tooltip links

- site/content/courses/12-001-introduction-to-geology-fall-2013/_index.md
- site/content/courses/15-071-the-analytics-edge-spring-2017/_index.md
- site/content/courses/15-s21-nuts-and-bolts-of-business-plans-january-iap-2014/_index.md
- site/content/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/_index.md
- site/content/courses/18-01sc-single-variable-calculus-fall-2010/_index.md
- site/content/courses/18-06-linear-algebra-spring-2010/_index.md
- site/content/courses/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/_index.md
- site/content/courses/21g-049-french-photography-spring-2017/_index.md
- site/content/courses/21m-250-beethoven-to-mahler-spring-2014/_index.md
- site/content/courses/21m-295-american-popular-music-fall-2014/_index.md
- site/content/courses/5-111sc-principles-of-chemical-science-fall-2014/_index.md
- site/content/courses/6-033-computer-system-engineering-spring-2018/_index.md
- site/content/courses/6-042j-mathematics-for-computer-science-spring-2015/_index.md
- site/content/courses/8-01sc-classical-mechanics-fall-2016/_index.md
- site/content/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/_index.md
- site/content/courses/8-06-quantum-physics-iii-spring-2005/_index.md
- site/content/courses/8-591j-systems-biology-fall-2014/_index.md
- site/content/courses/ec-711-d-lab-energy-spring-2011/_index.md
- site/content/courses/res-15-002-mission-metrics-finance-training-for-federal-credit-program-professionals-summer-2016/_index.md
- site/content/courses/res-15-003-shaping-the-future-of-work-15-662x-spring-2016/_index.md
- site/content/courses/res-2-005-girls-who-build-make-your-own-wearables-workshop-spring-2015/_index.md
- site/content/courses/res-2-006-girls-who-build-cameras-summer-2016/_index.md
- site/content/courses/res-3-004-visualizing-materials-science-fall-2017/_index.md
https://trello.com/c/kFngfkoX/28-course-by-topic-widget
https://trello.com/c/CBvQng2W/27-courses-feature-widget
Removes the content from the body section of the course home page markdown that is not in use anymore.
Generate some markdown, verify that only front matter is being written to the course home page `_index.md`.
> Remove course home body content

- package.json
- site/layouts/courses/section.html
no ticket
fixes an issue where the default course image wasn't working when deployed (it was, strangely, working locally...)
course images should all be working, whether it's one specific to a course or the default one.
> fix image issue

- site/content/courses/12-001-introduction-to-geology-fall-2013/_index.md
- site/content/courses/15-071-the-analytics-edge-spring-2017/_index.md
- site/content/courses/15-s21-nuts-and-bolts-of-business-plans-january-iap-2014/_index.md
- site/content/courses/16-01-unified-engineering-i-ii-iii-iv-fall-2005-spring-2006/_index.md
- site/content/courses/18-01sc-single-variable-calculus-fall-2010/_index.md
- site/content/courses/18-06-linear-algebra-spring-2010/_index.md
- site/content/courses/20-219-becoming-the-next-bill-nye-writing-and-hosting-the-educational-show-january-iap-2015/_index.md
- site/content/courses/21g-049-french-photography-spring-2017/_index.md
- site/content/courses/21m-250-beethoven-to-mahler-spring-2014/_index.md
- site/content/courses/21m-295-american-popular-music-fall-2014/_index.md
- site/content/courses/5-111sc-principles-of-chemical-science-fall-2014/_index.md
- site/content/courses/6-033-computer-system-engineering-spring-2018/_index.md
- site/content/courses/6-042j-mathematics-for-computer-science-spring-2015/_index.md
- site/content/courses/8-01sc-classical-mechanics-fall-2016/_index.md
- site/content/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/_index.md
- site/content/courses/8-06-quantum-physics-iii-spring-2005/_index.md
- site/content/courses/8-591j-systems-biology-fall-2014/_index.md
- site/content/courses/ec-711-d-lab-energy-spring-2011/_index.md
- site/content/courses/res-15-002-mission-metrics-finance-training-for-federal-credit-program-professionals-summer-2016/_index.md
- site/content/courses/res-15-003-shaping-the-future-of-work-15-662x-spring-2016/_index.md
- site/content/courses/res-2-005-girls-who-build-make-your-own-wearables-workshop-spring-2015/_index.md
- site/content/courses/res-2-006-girls-who-build-cameras-summer-2016/_index.md
- site/content/courses/res-3-004-visualizing-materials-science-fall-2017/_index.md
- site/layouts/partials/course_info.html
- site/layouts/partials/topic.html
- src/css/course-info.scss
https://trello.com/c/kFngfkoX/28-course-by-topic-widget
https://trello.com/c/bD5IxJqX/51-topics-widget-update
Adds a new hierarchial topics structure to sample markdown and the UI to display it in a new partial called "topic.html"
Run the site or check out the deploy preview.  Look at the different courses and make sure the topics look right and that you can expand / collapse the different levels.
> Topics widget

- site/layouts/courses/video.html
- src/css/main.scss
- src/css/video.scss
no ticket
implements a very basic video viewer page to allow you to see a video. no transcript for now, basically just the youtube player and the description.
try it out for a few videos and make sure it's working. linear algebra has a lot, like this one:
http://localhost:3000/courses/18-06-linear-algebra-spring-2010/sections/video-lectures/lecture-27-positive-definite-matrices-and-minima/
> very basic video viewer page

- package.json
- yarn.lock
no tickets, just a dependency upgrade. prompted by #126. tests should pass and all that, as long as they do and the app seems to work I think we're good.
> dependency upgrades

- site/content/courses/14-01sc-principles-of-microeconomics-fall-2011/_index.md
- site/content/courses/18-01sc-single-variable-calculus-fall-2010/_index.md
- site/content/courses/18-02sc-multivariable-calculus-fall-2010/_index.md
- site/content/courses/18-06sc-linear-algebra-fall-2011/_index.md
- site/content/courses/22-081j-introduction-to-sustainable-energy-fall-2010/_index.md
- site/content/courses/5-111sc-principles-of-chemical-science-fall-2014/_index.md
- site/content/courses/6-00sc-introduction-to-computer-science-and-programming-spring-2011/_index.md
- site/content/courses/6-042j-mathematics-for-computer-science-fall-2010/_index.md
- site/content/courses/6-042j-mathematics-for-computer-science-spring-2015/_index.md
- site/content/courses/6-046j-design-and-analysis-of-algorithms-spring-2015/_index.md
- site/content/courses/8-01sc-classical-mechanics-fall-2016/_index.md
- site/content/courses/8-03sc-physics-iii-vibrations-and-waves-fall-2016/_index.md
- site/content/courses/8-591j-systems-biology-fall-2014/_index.md
https://github.com/mitodl/hugo-course-publisher/issues/129
Updates the markdown with the output of https://github.com/mitodl/ocw-to-hugo/pull/44
Use the deploy preview below to verify the changes in the above PR.
> build the course number out of the proper data

- package.json
- src/index.js
- src/js/sentry.js
- yarn.lock
https://github.com/mitodl/hugo-course-publisher/issues/146
Adds code to initialize `@sentry/browser` with the `ocw-next` public DSN.
Pull down the branch, and temporarily insert this line in after `initSentry()` in `index.js`:
```js
throw new Error("TEST ERROR")
```
Change the message to something unique, and make sure it appears in the `ocw-next` Sentry log.
> Sentry support

- site/layouts/partials/header.html
https://trello.com/c/TmzWt97X/171-click-logo-to-go-home
Exactly what it says it does, add a link to `/courses` on the header logo.
Navigate to any page with the logo present and click it.
> /courses on logo click

- site/layouts/partials/header.html
- src/css/header.scss
https://github.com/mitodl/hugo-course-publisher/issues/170
Updates the header to match the new home page design.
Run the site and verify that the new header matches the new invision mock, located in the issue attached above.
> updated desktop header

- site/layouts/partials/header.html
- site/themes/multi_course/layouts/home.html
- src/css/header.scss
- src/css/home.scss
- src/css/main.scss
https://github.com/mitodl/hugo-course-publisher/issues/170
Adds mobile styles to the home page
Run the site or visit the deploy preview, verify that the sections implemented thus far match the mockup:
https://projects.invisionapp.com/d/main#/console/18552410/427793030/inspect?scrollOffset=681.25
> mobile home page

- src/js/lib/search.js
- src/js/lib/search.test.js
messed up (by me!) here: https://github.com/mitodl/hugo-course-publisher/commit/ca9c3e6690c4d758c1e7e26cf7c3e908efe337e4#diff-056cfd3919133e6120edb4d9c64a6501L132-L140
make it so that we return query for courses which have resources which match the query, not just the courses themselves.
there is a test search of 'albedo': on master you should see no results for this, but on this PR some should come back.
> fix search issue w/ course resources

- package.json
- yarn.lock
> grab latest version of course-search-utils

- build-scripts/import_ocw.sh
- package.json
- yarn.lock
None
Updates the `ocw-to-hugo` dependency to 1.0.9
Run `import:ocw` based on the instructions in the readme for the example courses and ensure you don't get any errors.
> ocw to hugo 1.0.9

- package.json
- src/js/components/SearchPage.test.js
- yarn.lock
none
upgrade to the latest version of course-search-utils to fix an issue where three search request were mistakenly being made on load. See https://github.com/mitodl/course-search-utils/issues/7 for details.
read that issue, and confirm the presence of the problem. then confirm that upgrading the package fixes it.
> upgrade @mitodl/course-search-utils

- package.json
None
Lints build scripts
Add an extra variable to one of the build scripts, then run `npm run lint`. You should see a lint error.
> Lint build scripts too

- package.json
- yarn.lock
None
This PR updates the `ocw-to-hugo` dependency to version 1.0.11
Perform a full `import:ocw` run and ensure the expected markdown is generated and deposited in `site/content`
> ocw-to-hugo 1.0.11

- site/layouts/shortcodes/video-gallery-item.html
- src/css/video.scss
Related to #182 
Converts video markdown generated by ocw-data-parser (https://github.com/mitodl/ocw-to-hugo/pull/106) to HTML
Generate the necessary input for course `ec-711-d-lab-energy-spring-2011` via ocw-data-parser and replace the content of `output/courses/ec-711-d-lab-energy-spring-2011/sections/intro-energy-basics-human-power/_index.md` with this (or run ocw-data-parser via PR https://github.com/mitodl/ocw-to-hugo/pull/106):
```
---
title: 'Week 1: Introduction, Energy Basics & Human Power'
course_id: ec-711-d-lab-energy-spring-2011
type: course
layout: course_section
menu:
ec-711-d-lab-energy-spring-2011:
identifier: 32a22e0de0add67342ce41445297fce7
name: 'Introduction, Energy Basics & Human Power'
weight: 20
is_media_gallery: true
---
{{< video-gallery-item …
```
> New shortcode for video gallery items

- src/js/components/Facet.js
- src/js/components/FacetDisplay.js
- src/js/components/SearchPage.js
none
1. move level to be facet no. 1
2. use a 'normal' filter for it instead of our filterable one.
check out the branch and ensure the level facet works well and follows those two things.
> fix a few level facet issues

- site/layouts/shortcodes/video-gallery-item.html
- src/css/video.scss
None
Releases latest code from `release-candidate`
> 10/26/2020 Release

- src/index.js
Fixes #296 
Imports bootstrap in `src/index.js` which initializes the bootstrap javascript, enabling the carousel transitions.
Click on the previous and next buttons on the carousel
> Import bootstrap JS to fix carousel buttons

- site/layouts/partials/newsletter_signup.html
- site/themes/multi_course/layouts/home.html
- src/index.js
- src/js/mailchimp.js
Fixes #283 
Implements mailchimp signup. We need to add `MAILCHIMP_USER_ID` and `MAILCHIMP_AUDIENCE_ID` environment variables to make this work and have them be present when hugo is run.
- Create a mailchimp account and get the user and audience ID. You can find these by going to the mailchimp dashboard and then clicking on Audience => Signup Forms => Embedded Forms => Condensed, for example. In the `action` attribute of `form` there is a url. The `u=` part is the user id and the `id=` is the audience id.
- Set these values to `MAILCHIMP_USER_ID` and `MAILCHIMP_AUDIENCE_ID` in `.env`
- Run `docker-compose up`
- Fill out the email signup form at the bottom. You should see a success message or some variety of failure message.
- You should be able to both press enter to submit and click the …
> Implement Mailchimp signup

- src/css/header.scss
closes #371
change the height of the header.
just check that all pages look alright.
> design tweak: header height to 70px

- site/layouts/partials/course_features.html
- site/layouts/partials/course_info.html
None
Fixes a build error
Run `npm run build:zips` with a collection of courses. It should pass.
> Add back check for course_info params

- site/layouts/partials/course_features.html
- site/layouts/partials/course_info.html
- site/layouts/partials/topic.html
- site/layouts/partials/topics.html
- site/layouts/partials/topics_oneline.html
- src/css/course-home.scss
closes #382 
closes #384
restyles the topic font-weight and the titles / spacing in the course info
look at the course info on both mobile and on desktop and make sure that things look alright!
> design tweaks

- site/themes/multi_course/layouts/home.html
closes #399
delete the little arrow on the home page
check it out
> remove small arrow on home page

- site/layouts/partials/topic.html
- site/layouts/partials/topics_oneline.html
closes #398
just makes the topics look like links.
make sure it looks like a link! the topics on both the course home and on the course section pages
> fix link styling

- site/layouts/course/course_home.html
- src/css/course-home.scss
Fixes an accidental change to the font for the course description title
Changes the colors to match the mockup
Look at the course description title on the course home page
> Fix course description title

- site/layouts/course/baseof.html
- site/layouts/partials/desktop_course_info.html
- site/layouts/search/section.html
none
I just took a stab at putting `partialCached` intead of `partial` in a few places where it might help us out. I got a small boost from caching the course info partials (I added one for the desktop course into to make it easier to cache). Both are cached under the course ID as a cache key, because the rendered templates should be the same for every page in the course.
I also added caching to a few partials which don't change no matter the course they're rendered on, like the header partial and so on.
That gave me a roughly ~15% speedup in hugo build time - times varied a little bit, but it took the build from ~12-13s to ~10 (this is running off of the courses in the `example_courses.json` file). We should see an equivalent drop in build times for the whole course set, I should think. …
> sprinkle partialCached here and there

- site/layouts/partials/home_course_cards.html
closes #370
just adjusts the padding on a few elements.
I think just check it out and make sure it all looks alright.
> tweak padding in course home page card

- src/js/course_expander.js
None
Fixes a typo
Nothing should change (except in the console)
> Remove console.log
